name: Configuration Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit-tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: install nginx
        run: apt install nginx -y

      - name: Validate nginx config
        run: |
          sudo cp nginx/my-app.conf /etc/nginx/conf.d/default.conf
          sudo nginx -t