name: Integration test
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build the test environtment
        run: |
          cat <<EOF > .env
          IMMICH_VERSION=release
          UPLOAD_LOCATION=./uploads
          DB_DATA_LOCATION=./db
          DB_PASSWORD=test
          DB_USERNAME=postgres
          DB_DATABASE_NAME=immich
          EOF
      
      - name: Start container
        run: docker compose up -d -f docker/docker-compose.yaml

      - name: Wait for service startup
        run: sleep 20

      - name: Test nginx proxy
        run: curl -f http://localhost:80

      - name: Show logs on failure
        if: failure()
        run: docker compose logs